### PR TITLE
static search with pagefind

### LINKED ISSUE #31: Full site search
right now https://webdocs.dev/en-us/search?q=foo doesn't work because that depends on the "api" which we can't host statically

we do have page title search which works well in most cases.

our options for this include:
- {redirecting to/adding an iframe for/using the API of} a search engine. right now webdocs.dev isn't indexed by any search engines though...
- hijacking developer.mozilla.org for the API
- setting up a separate hosting platform for API requests
- switching to a different hosting method for the whole site
- just disable full site search (and maybe return to it later)

edit:
- https://pagefind.app seems like a good solution

### PR DESCRIPTION
**Pull request by pommicket**
resolves #31 

this PR adds support for static full site search through pagefind. to enable it, set `REACT_APP_SEARCH_BACKEND` to `"pagefind"` in `.env`.
you can build the index with `yarn tool build-pagefind-index` (after running `yarn build`).

to make things easier to set up, i've also added a `yarn build:static` command which runs `yarn build` as well as everything else needed to get the static site working.

### CODE REVIEW

File: tool/fix-urls-for-static-hosting.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+import child_process, { spawnSync } from "node:child_process";
```
Comment (sideshowbarker) [inline tool/fix-urls-for-static-hosting.ts]:
```suggestion
import { spawnSync } from "node:child_process";
```

File: tool/fix-urls-for-static-hosting.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+import fs from "node:fs";
+import util from "node:util";
```
Comment (sideshowbarker) [inline tool/fix-urls-for-static-hosting.ts]:
```suggestion
```

File: tool/fix-urls-for-static-hosting.ts [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+import { BUILD_OUT_ROOT } from "../libs/env/index.js";
+
+export function runFixUrlsForStaticHosting(options) {
```
Comment (sideshowbarker) [inline tool/fix-urls-for-static-hosting.ts]:
```suggestion
export function runFixUrlsForStaticHosting(options) {
```
Should we remove the `options` argument from the signature? [And from the call site(s)…]

File: client/src/site-search/search-results.tsx [hunk 4]
```diff
@@ -84,6 +87,82 @@ class ServerOperationalError extends Error {
...
+  // from messing with this or complaining that the module doesn't exist.
+  // eslint-disable-next-line no-eval
+  const pagefind = await eval(
+    // eslint-disable-next-line no-template-curly-in-string
+    "import(`/static/js/pagefind/${locale}/pagefind.js`)"
+  );
+  const search = await pagefind.search(params.get("q"));
+  const resultsPerPage = 10;
+  let page = parseInt(params.get("page"));
+  if (page <= 0 || isNaN(page)) page = 1;
```
Comment (Sorixelle) [inline client/src/site-search/search-results.tsx]: nit:
```typescript
const page = parseInt(params.get("page")) || 1;
```

File: client/src/site-search/search-results.tsx [hunk 5]
```diff
@@ -84,6 +87,82 @@ class ServerOperationalError extends Error {
...
+        )
+      : [];
+  const documents = results.map((result) => {
+    return {
+      mdn_url: `/${locale}/docs${result.url}`,
+      title: result.meta.title,
+      // note: summary is unused when highlight is non-empty
+      // and we don't have a good way of getting a summary
+      // without doing quite a bit of work
+      // (in particular, result.meta.content has HTML tags)
```
Comment (Sorixelle) [inline client/src/site-search/search-results.tsx:142]: Maybe mark this comment explicitly as TODO, since we would probably want to get around to that at some point.

**Review by Sorixelle — CHANGES_REQUESTED** [review]

File: client/src/site-search/search-results.tsx (hunk 5 above)
Comment (pommicket) [reply client/src/site-search/search-results.tsx:142]: it would be completely useless unless the `Results` function is changed in the future... i'm just not sure it's worth the effort of figuring out which HTML tags contain text, etc.

Comment (Sorixelle) [reply client/src/site-search/search-results.tsx:142]: Ah - my bad, think I misunderstood what that field was for.

**Review by Sorixelle — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]
